# Generated by Django 5.2.5 on 2025-08-10 12:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('actor', 'Actor'), ('filmmaker', 'Filmmaker')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FilmmakerProfile',
            fields=[
                ('filmmaker_profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True)),
                ('information', models.TextField(blank=True)),
                ('movies_done', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmmaker_profiles', to='API.user')),
            ],
        ),
        migrations.CreateModel(
            name='ActorProfile',
            fields=[
                ('actor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills', models.TextField(blank=True)),
                ('headshots', models.ImageField(blank=True, null=True, upload_to='headshots/')),
                ('availability', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_profiles', to='API.user')),
            ],
        ),
    ]
