# Generated by Django 5.2.5 on 2025-08-10 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_user_is_profile_complete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actorprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='actorprofile',
            name='headshots',
        ),
        migrations.AddField(
            model_name='actorprofile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='actorprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actorprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actorprofile',
            name='profile_picture',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='actorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='actorprofile',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='actorprofile',
            name='skills',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='filmmakerprofile',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='filmmakerprofile',
            name='information',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='filmmakerprofile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
