# Generated by Django 5.2.5 on 2025-08-12 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_actorprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmmakerprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='filmmakerprofile',
            name='availability',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='filmmakerprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='filmmakerprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filmmakerprofile',
            name='profile_picture',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='filmmakerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
