# Generated by Django 5.2.5 on 2025-08-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_filmmakerprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmmakerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='filmmakerprofile',
            name='status',
        ),
    ]
