# Generated by Django 5.2.5 on 2025-08-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_filmmakerprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarStore',
            fields=[
                ('uid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('avatarId', models.CharField(max_length=255, unique=True)),
                ('avatarUrl', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avatar Store',
                'verbose_name_plural': 'Avatar Store',
                'ordering': ['-created_at'],
            },
        ),
    ]
